im:
  tcpPort: 8002
  webSocketPort: 18002
  bossThreadSize: 1
  workerThreadSize: 8
  hearBeatTime: 3000
  brokerId: 1002
  loginModel: 1

  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password: 123
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 192.168.181.128:6379

  rocketmq:
    address: 192.168.181.128:9876

  nacos:
    address: 192.168.181.128:8848
    namespace: c65a45b8-9b55-4b53-9e10-fbab776f8db6
    username: nacos
    password: nacos
