server:
  port: 8000

spring:
  application:
    name: business
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.181.128:3306/im-core?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ypj.,?/0102

mybatis-plus:
  mapper-locations: classpath:**/mapper/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: NONE
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.lld.im.service.user.dao: debug
    com.baomidou.mybatisplus: debug

nacos:
  address: 192.168.181.128.8848
  namespace: c65a45b8-9b55-4b53-9e10-fbab776f8db6
  username: nacos
  password: nacos